name = '0jewell/tdkit'
version = '0.1.0'
authors = ['0jewell']
repository = 'https://github.com/0jewell/td-kit'
license = 'MIT'

includes = ['src', 'pesde.toml', 'pesde.lock']

[target]
environment = 'roblox'
lib = 'src/init.luau'
build_files = ['src']

[indices]
default = 'https://github.com/pesde-pkg/index'

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dependencies]
rojo = { name = 'pesde/rojo', version = '^7.5.1', target = 'lune' }