name = '0jewell/tdkit'
description = 'Roblox Tower Defense utilities'
version = '0.1.1'
authors = ['0jewell']
repository = 'https://github.com/0jewell/td-kit'
license = 'MIT'

includes = ['src/*', 'LICENSE', 'README.md', 'pesde.toml']

[target]
environment = 'roblox'
lib = 'src/init.luau'
build_files = ['src']

[indices]
default = 'https://github.com/pesde-pkg/index'

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
rojo = { name = 'pesde/rojo', version = '^7.5.1', target = 'lune' }